import { Injectable } from '@angular/core';
import { HttpErrorResponse, HttpResponse} from '@angular/common/http';
import { HttpClient } from '@angular/common/http';
import { catchError, retry } from 'rxjs/operators';
import { Observable, throwError } from 'rxjs';

export interface Config {
  token: string;
  name: string;
  role: string;
}

@Injectable({
  providedIn: 'root'
})
export class HandleErrorService {

    configUrl = 'dsfsd/fsdfsdf/fsdfsd';

    constructor(private http: HttpClient) { }

    getConfigResponse(): Observable<HttpResponse<Config>> {
      return this.http.get<Config>(
        this.configUrl, { observe: 'response' });
    }

    public handleError(error: HttpErrorResponse) {
        if (error.error instanceof ErrorEvent) {
          // A client-side or network error occurred. Handle it accordingly.
          console.error('An error occurred:', error.error.message);
        } else {
          // The backend returned an unsuccessful response code.
          // The response body may contain clues as to what went wrong,
          console.error(
            `Backend returned code ${error.status}, ` +
            `body was: ${error.error}`);
        }
        // return an observable with a user-facing error message
        return throwError(
          'Something bad happened; please try again later.');
    }

    makeIntentionalError() {
      return this.http.get('not/a/real/url')
        .pipe(
          catchError(this.handleError)
        );
    }

}
